task :build do
  sh "gem build keycloak.gemspec"
end

task :install => [:build] do
  sh "gem install libkeycloak*.gem"
end

task :clean do
  sh 'rm libkeycloak*.gem'
end

task :test, [:user, :pass] do
  user = ARGV[1]
  pass = ARGV[2]
  Dir.chdir("../..") do
    sh "LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH:$(pwd)/build\" ruby example.rb #{user} #{pass}"
  end
end

# User and pass for testing
task :publish, [:user, :pass] => [:clean, :build, :install, :test] do
  sh "gem push libkeycloak*.gem"
end
